# Generated by Django 5.2.3 on 2025-06-17 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('insurance_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_name', models.CharField(max_length=100, verbose_name='Název pojištění')),
                ('insurance_description', models.TextField(verbose_name='Popis pojištění')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktivní')),
            ],
            options={
                'verbose_name': 'Insurance Type',
                'verbose_name_plural': 'Insurance Types',
                'ordering': ['insurance_name'],
            },
        ),
        migrations.CreateModel(
            name='Insured_person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_registration', models.DateTimeField(auto_now_add=True)),
                ('date_last_modification', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insured person',
                'verbose_name_plural': 'Insured persons',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_number', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='pojistovna.insurancetype')),
                ('insured_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='pojistovna.insured_person')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
                'ordering': ['-start_date'],
            },
        ),
    ]
