# Generated by Django 5.2.3 on 2025-06-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetype',
            name='insurance_type_id',
        ),
        migrations.AddField(
            model_name='insurancetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
