# Generated by Django 5.2.3 on 2025-06-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0002_remove_insurancetype_insurance_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insured_person',
            name='password',
        ),
    ]
