# Generated by Django 5.2.3 on 2025-06-19 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0003_remove_insured_person_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insured_person',
            new_name='InsuredPerson',
        ),
    ]
