# Generated by Django 5.2.3 on 2025-06-19 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0004_rename_insured_person_insuredperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_number',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pojistovna.insurance')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
