# Generated by Django 5.2.3 on 2025-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0005_alter_insurance_insurance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Cena pojištění'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_subject',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Předmět pojištění'),
        ),
    ]
