# Generated by Django 5.2.3 on 2025-06-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0006_insurance_insurance_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Insurance price'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_subject',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Insurance subject'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
