# Generated by Django 5.2.3 on 2025-06-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0007_alter_insurance_insurance_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='damage_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='event',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-25'),
            preserve_default=False,
        ),
    ]
