# Generated by Django 5.2.3 on 2025-07-13 11:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0008_event_damage_amount_event_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_number',
            field=models.CharField(default=uuid.UUID('c6dbfcc0-2fea-430a-b13f-9919e3da4ce7'), max_length=20, unique=True),
        ),
    ]
