# Generated by Django 5.2.3 on 2025-07-13 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0009_alter_event_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_number',
            field=models.CharField(default=uuid.UUID('de1db61f-668b-4d1a-a3c7-546274433651'), max_length=20, unique=True),
        ),
    ]
