# Generated by Django 5.2.3 on 2025-07-14 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna', '0010_alter_insurance_insurance_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_number',
            field=models.CharField(default=uuid.UUID('630fdedb-58bf-4fc4-87a2-7f15bcd12b7f'), max_length=20, unique=True),
        ),
    ]
